Added css file; fixed errors like
<input type="text" >ERROR   (2006-01-08) 17:19.26:938   [sitemap.handled-errors] (/exist/admin/error.css) http-8080-Processor24/ErrorHandlerHelper: Error during resolving of the input stream
org.apache.cocoon.ResourceNotFoundException: Error during resolving of the input stream: org.apache.excalibur.source.SourceNotFoundException: file:/C:/Program Files/Apache Software Foundation/Tomcat 5.5/webapps/exist/admin/error.css doesn't exist.
	at org.apache.cocoon.components.source.SourceUtil.handle(SourceUtil.java:421)

svn path=/trunk/eXist-1.0/; revision=2489


Former-commit-id: 3ec045e98efc1c0944d9eeda4668d81fb214dbfd