[bugfix] When eXist was started in client/embedded mode, org.exist.xquery.value.Base64BinaryValueType was complaining with java.lang.NoClassDefFoundError about lack of org.apache.commons.codec.binary.Base64OutputStream , which is inside lib/optional/commons-codec-1.4.jar . The fix has been adding a new line for that case in src/org/exist/start/start.config
svn path=/trunk/eXist/; revision=13422


Former-commit-id: 84aee068430ea939318a3365f359085947126d65